#+title: KIITOS/3

* *Migrated to Codeberg*
Kiitos can now be found at [[https://codeberg.org/celesteornato/KiitOS]]


* The better-structured sequel to Kiitos/2, the OS with absolutely no correlation to OS/2
This is the full rework of the original Kiitos/2 from early 2025, now with
an even better codebase, at the great cost of no longer having any code.
We support GNU Make now, and at some point maybe the makefile will be good.

Also I still don't have a shell lol

Good OS anyways, Doom when

* Dependencies
** Minimal requirements
Do not use just that, please.
+ A C compiler for x86_64-unknown-none
+ An x86_64 assembler
** Probably needed for the barebones
+ clang/gcc
  + gcc will probably work for the forseeable future, however the officially-supported
    compiler is clang at ~-O2~.
+ xorriso
+ git
  + Only required for the first ever ~make~, so as to clone and
    build the limine bootloader.
    The limine repo will not get deleted on ~make clean~-ing.
+ Some ~make~, either GNU or BSD
  + Yes, I bothered making it compatible. Yes, it looks ugly.
    If you ask me the GNU syntax is uglier.
** Recommended
+ clang
+ xorriso
+ git
+ make (bmake)
+ qemu
+ gdb
